## -------- Build stage ----------------------------------------------------
FROM node:18-alpine AS builder
WORKDIR /app

ARG MORALIS_API_KEY
ARG ALCHEMY_API_KEY

COPY package*.json ./
RUN npm ci

COPY . .

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    MORALIS_API_KEY=$MORALIS_API_KEY \
    ALCHEMY_API_KEY=$ALCHEMY_API_KEY

RUN npm run build:testnet

##
## -------- Runtime stage --------------------------------------------------
##
FROM node:18-slim AS runtime
WORKDIR /app


ENV NODE_ENV=production \
    PORT=32101

COPY --from=builder /app/.next/standalone        ./
COPY --from=builder /app/.next/static            ./.next/static
COPY --from=builder /app/public                  ./public

EXPOSE 32101
CMD ["node", "server.js"]