name: Build & Push Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-version:
    name: Generate Semantic Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_tag: ${{ steps.version.outputs.version_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: 'v'
          major_pattern: '(MAJOR)'
          minor_pattern: '(feat|feature)'
          version_format: '${major}.${minor}.${patch}'

  build:
    runs-on: ubuntu-latest
    needs: [generate-version]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push mainnet
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_mainnet
          push: true
          platforms: linux/amd64
          build-args: |
            MORALIS_API_KEY=${{ secrets.MORALIS_API_KEY }}
            ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}
            NEXT_PUBLIC_APP_VERSION=${{ needs.generate-version.outputs.version }}
          tags: |
            ratio1/explorer:mainnet


