name: Build & Push Devnet Image

on:
  push:
    branches: [ develop ]
  # also allow manual runs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Devnet Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_devnet
          push: true
          platforms: linux/amd64
          build-args: |
            MORALIS_API_KEY=${{ secrets.MORALIS_API_KEY }}
            ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}
            NEXT_PUBLIC_COMMIT_HASH=${{ github.sha }}
          tags: |
            ratio1/explorer:devnet
