name: Create Multi-Release on Main Push

on:
    push:
        branches:
            - main

jobs:
    install-dependencies:
        name: Install Dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-${{ runner.os }}-

    build-and-release:
        name: Build and Release
        runs-on: ubuntu-latest
        needs: install-dependencies
        strategy:
            matrix:
                network: [devnet, testnet, mainnet]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Restore node_modules cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-${{ runner.os }}-

            - name: Build Next.js app for ${{ matrix.network }}
              run: npm run build:${{ matrix.network }}

            - name: Archive production build
              run: tar -czvf nextjs-build-${{ matrix.network }}.tar.gz .next

            - name: Generate version from commit hash
              id: version
              run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.version.outputs.VERSION }}-${{ matrix.network }}
                  name: Release v${{ steps.version.outputs.VERSION }} (${{ matrix.network }})
                  draft: false
                  prerelease: false
                  files: nextjs-build-${{ matrix.network }}.tar.gz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
